name: Unit Tests and Coverage

on:
  push:
    branches:
      - main
      - testnet
  pull_request:
    branches: [master, testnet]

jobs:
  Jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run Tests
        run: |
          npm install --legacy-peer-deps
          npm test
